/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import static Ventanas.Principal.matriz;
import proyecto_1.Lista;

/**
 *
 * @author valery
 */
public class ReporteAlmacen extends javax.swing.JFrame {

    public static Principal v1;
    
    public ReporteAlmacen(Principal v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dfsboton = new javax.swing.JButton();
        bfsboton = new javax.swing.JButton();
        volver = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bfsTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dfsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("REPORTES POR ALMACEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 60));

        dfsboton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dfsboton.setText("DFS");
        dfsboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsbotonActionPerformed(evt);
            }
        });
        jPanel1.add(dfsboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 140, 40));

        bfsboton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bfsboton.setText("BFS");
        bfsboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsbotonActionPerformed(evt);
            }
        });
        jPanel1.add(bfsboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 140, 40));

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 10, 100, -1));

        bfsTextArea.setColumns(20);
        bfsTextArea.setRows(5);
        jScrollPane2.setViewportView(bfsTextArea);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 120));

        dfsTextArea.setColumns(20);
        dfsTextArea.setRows(5);
        jScrollPane1.setViewportView(dfsTextArea);

        jScrollPane4.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 290, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Principal ventana1= new Principal();
        this.setVisible(false);
        ventana1.setVisible(true);
        
    }//GEN-LAST:event_volverActionPerformed

    private void dfsbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsbotonActionPerformed
        Lista visitadosDfs = matriz.Dfs(matriz, "A");
//        this.bfsTextArea.setText(visitadosDfs.printProductos());
    }//GEN-LAST:event_dfsbotonActionPerformed

    private void bfsbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsbotonActionPerformed
        Lista visitadosBfs = matriz.Bfs(matriz, "A");
//        this.bfsTextArea.setText(visitadosBfs.printProductos());
    }//GEN-LAST:event_bfsbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteAlmacen(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bfsTextArea;
    private javax.swing.JButton bfsboton;
    private javax.swing.JTextArea dfsTextArea;
    private javax.swing.JButton dfsboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton volver;
    // End of variables declaration//GEN-END:variables
}
