/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import proyecto_1.Grafo;
import proyecto_1.Vertice;
import proyecto_1.ListaSimple;
import proyecto_1.Nodo;
import static Ventanas.Principal.matriz;
import javax.swing.JOptionPane;
import proyecto_1.Funciones;
import proyecto_1.Stock_produc;
import proyecto_1.helpers;

public class OrderWindow extends javax.swing.JFrame {

    
    public OrderWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        showProducts = new javax.swing.JButton();
        nameProduct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantityProduct = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        vertex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Realizar Pedido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        screen.setColumns(20);
        screen.setRows(5);
        screen.setFocusable(false);
        jScrollPane1.setViewportView(screen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 540, 160));

        showProducts.setText("Ver Productos");
        showProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductsActionPerformed(evt);
            }
        });
        jPanel1.add(showProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        nameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProductActionPerformed(evt);
            }
        });
        jPanel1.add(nameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, -1));

        jLabel2.setText("Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel1.add(quantityProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 290, -1));

        Order.setText("Ingresar Pedido");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        jPanel1.add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 130, -1));

        vertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertexActionPerformed(evt);
            }
        });
        jPanel1.add(vertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 290, -1));

        jLabel4.setText("Almacen:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setText("Ingrese el nombre del producto que desea, la cantidad y el almacen donde desea retirar su pedido.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProductActionPerformed

    private void showProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProductsActionPerformed
        Funciones func = new Funciones();
        String info = func.showProduct(matriz);
        screen.setText(info);
    
    }//GEN-LAST:event_showProductsActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        helpers help = new helpers();
        ListaSimple list = new ListaSimple();
        ListaSimple lista = new ListaSimple();
        for (int i = 0; i < matriz.getNumVerts(); i++) {
             ListaSimple list2 = (ListaSimple) matriz.vertice(i).getElement();
             int cont = 0;
             while(list2.getSize() > cont){
                Stock_produc product = (Stock_produc) list2.getValor(cont);
                String namePro = product.getName();
                list.InsertarFinal(namePro);
                cont++;
             }
            
        }
        for (int i = 0; i < matriz.getNumVerts(); i++) {
            String name = matriz.vertice(i).getName();
            lista.InsertarFinal(name);
        }
        if (!list.buscar(nameProduct.getText()) || help.ValidarNumeros(quantityProduct.getText()) == -1 || !lista.buscar(vertex.getText())){
            JOptionPane.showMessageDialog(null, "Opción errónea");
        } else{
//            Funcion de RealizarPedido()
        }
        
    }//GEN-LAST:event_OrderActionPerformed

    private void vertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vertexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JTextField quantityProduct;
    private javax.swing.JTextArea screen;
    private javax.swing.JButton showProducts;
    private javax.swing.JTextField vertex;
    // End of variables declaration//GEN-END:variables
}
