/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import proyecto_1.Funciones;
import proyecto_1.Grafo;

/**
 *
 * @author moise
 */
public class Principal extends javax.swing.JFrame {

    public static Funciones func;
    public static Grafo matriz;

    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO_Principal = new javax.swing.JLabel();
        titulo_mENU = new javax.swing.JLabel();
        cargartxt = new javax.swing.JButton();
        gestion_info = new javax.swing.JButton();
        realizar_pedido = new javax.swing.JButton();
        recorridos = new javax.swing.JButton();
        mostrar_grafo = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        TITULO_Elaboracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO_Principal.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TITULO_Principal.setText("Organized Chaos");
        jPanel1.add(TITULO_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        titulo_mENU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo_mENU.setText("MENÚ");
        jPanel1.add(titulo_mENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, 40));

        cargartxt.setText("Cargar Archivo");
        cargartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargartxtActionPerformed(evt);
            }
        });
        jPanel1.add(cargartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        gestion_info.setText("Gestion de Info.");
        gestion_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_infoActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        realizar_pedido.setText("Realizar Pedido");
        realizar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizar_pedidoActionPerformed(evt);
            }
        });
        jPanel1.add(realizar_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        recorridos.setText("Disponibilidad");
        recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorridosActionPerformed(evt);
            }
        });
        jPanel1.add(recorridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, -1));

        mostrar_grafo.setText("Mostrar Grafo");
        jPanel1.add(mostrar_grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 50, 40));

        TITULO_Elaboracion.setText("Elaborado por: Valeria Carmona, José Hurtado y Moisés Liota");
        jPanel1.add(TITULO_Elaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 340, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cargartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargartxtActionPerformed
        Cargar_Datos v2 = new Cargar_Datos(this);
        v2.setVisible(true);
    }//GEN-LAST:event_cargartxtActionPerformed

    private void recorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorridosActionPerformed
        ReporteAlmacen ventana= new ReporteAlmacen(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_recorridosActionPerformed

    private void gestion_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_infoActionPerformed
        GestionInfo gestion_info = new GestionInfo(this);
        this.setVisible(false);
        gestion_info.setVisible(true);
    }//GEN-LAST:event_gestion_infoActionPerformed

    private void realizar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizar_pedidoActionPerformed
        OrderWindow window = new OrderWindow(this);
        this.setVisible(false);
        window.setVisible(true);
    }//GEN-LAST:event_realizar_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO_Elaboracion;
    private javax.swing.JLabel TITULO_Principal;
    private javax.swing.JButton cargartxt;
    private javax.swing.JButton exit;
    private javax.swing.JButton gestion_info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrar_grafo;
    private javax.swing.JButton realizar_pedido;
    private javax.swing.JButton recorridos;
    private javax.swing.JLabel titulo_mENU;
    // End of variables declaration//GEN-END:variables
}
